blog/urls.py
from django.urls import path
from blog.views import (PostListView,CommentDeleteView,
                        ReplyDeleteView,
                       PostDetailView,CategoryPostListView,
                       TagPostListView,SearchPostListView,
                       CommentCreateView,ReplyCreateView)

urlpatterns = [path("", PostListView.as_view(), name='Post-List'),
               path("post/<int:pk>/",PostDetailView.as_view(), name='post-Detail'),
               path("category/<str:slug>", CategoryPostListView.as_view(),name='category-Post-List'),
               path("tag/<str:slug>", TagPostListView.as_view(),name='tag-Post-List'),
               path("search/",SearchPostListView.as_view(),name='search-Post-List'),
               path("comment/<int:post_pk>",CommentCreateView.as_view(),name='comment'),
               path("reply/<int:comment_pk>",ReplyCreateView.as_view(),name='reply'),
               path("comment/<int:pk>/delete/",CommentDeleteView.as_view(),name='comment-delete'),
               path("reply/<int:pk>/delete/",ReplyDeleteView.as_view(),name='reply-delete'),
               
]
               

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    ]

if settings.DEBUG:
   urlpatterns += static(
       settings.MEDIA_URL,document_root = settings.MEDIA_ROOT
   ) 

blog/models.py
from django.db import models




class Category (models.Model):
    name =models.CharField("カテゴリー",max_length=255)
    slug = models.SlugField("URL",unique=True)
    
    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name_plural = "カテゴリー"
    
class Tag (models.Model):
    name =models.CharField("タグ",max_length=255)
    slug = models.SlugField("URL",unique=True)
    
    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name_plural = "タグ"
    
class Post (models.Model):
    title = models.CharField("タイトル", max_length=200)
    description = models.TextField("本文", blank=True)
    image = models.ImageField('画像',upload_to='upload/',null=True,blank=True)
    created_at = models.DateField( "作成日", auto_now_add=True)
    updated_at = models.DateField( "更新日",auto_now=True)
    is_published = models.BooleanField("公開設定",default=False)
    
    
    category = models.ForeignKey(Category,verbose_name="カテゴリー",on_delete=models.PROTECT,null=True,blank=True)    
    tag = models.ManyToManyField(Tag,verbose_name="タグ",blank=True)
    def __str__(self):
            return self.title
        
    class Meta:
        verbose_name_plural = "ポスト"
        
class Comment(models.Model):
    name = models.CharField("名前",max_length=100)
    text = models.TextField("本文")
    created_at = models.DateField( "作成日", auto_now_add=True)
    post = models.ForeignKey(Post,verbose_name="記事",on_delete=models.CASCADE)    
   
    def __str__(self):
        return self.text[:10]
    class Meta:
        verbose_name_plural = "記事"
        
class Reply(models.Model):
    name = models.CharField("名前",max_length=100)
    text = models.TextField("本文")
    created_at = models.DateField( "作成日", auto_now_add=True)
    comment = models.ForeignKey(Comment,verbose_name="返信",on_delete=models.CASCADE)    
   
    def __str__(self):
        return self.text[:10]
    class Meta:
        verbose_name_plural = "コメント"

blog/forms.py
from django import forms
from blog.models import Comment,Reply


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("name", "text")
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': '名前', 'class': 'form-control'}),
            'text': forms.Textarea(attrs={'placeholder': 'コメントを入力してください', 'class': 'form-control'}),
        }
        
        labels = {
            'name':'*必須',
            'text':'*必須',
            
        }

        
class ReplyForm(forms.ModelForm):
    class Meta:
        model = Reply
        fields = ("name","text")
        widgets = {
            'name':forms.TextInput(attrs={'placeholder':'名前','class':'form-control'}),
            'text':forms.Textarea(attrs={'placeholder':'返信を入力してください','class':'form-control'}),
        }
        
        labels = {
            'name':'*必須',
            'text':'*必須',
            
        }

        

blog/views.py
from typing import Any
from django.db.models.base import Model as Model
from django.db.models.query import QuerySet
from django.forms import BaseModelForm
from django.shortcuts import render,get_object_or_404,redirect
from django.http import Http404, HttpResponse
from django.db.models import Q
from django.urls import reverse_lazy,reverse
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.


from django.views.generic import ListView,DetailView,CreateView,DeleteView
from blog.forms import CommentForm,ReplyForm
from .models import Post,Category,Tag,Comment,Reply



class PostListView(ListView):  # データベースの一覧を標示
    model = Post
    template_name = "blog/post_list.html"
    context_object_name = "post"
    paginate_by = 5
    
    #更新順に並び替える
    def get_queryset(self):
        posts = super().get_queryset()
        
        return  posts.order_by("-updated_at")


class PostDetailView(DetailView):#データベースの詳細を表示
    model = Post
    template_name = "blog/post_detail.html"
    paginate_by = 5
    
    def get_object(self, queryset=None):
        post = super().get_object(queryset)
        #公開済み　or　ログインしている人だけ公開
        if post.is_published or self.request.user.is_authenticated:
                                    
            return post 
        else:
            raise Http404
        
class CategoryPostListView(ListView):
    model = Post
    template_name = "blog/post_list.html"
    context_object_name = "post"
    paginate_by = 5
    
    def get_queryset(self):
        slug = self.kwargs['slug']
        self.category = get_object_or_404(Category,slug =slug)
        
       
        return  super().get_queryset().filter(category = self.category)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
       
        
        context["category"] = self.category
        return context
    
class TagPostListView(ListView):
    model = Post
    template_name = "blog/post_list.html"
    context_object_name = "post"
    paginate_by = 5
    
    def get_queryset(self):
        slug = self.kwargs['slug']
        self.tag = get_object_or_404(Tag,slug =slug)
        
       
        return  super().get_queryset().filter(tag = self.tag)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["tag"] = self.tag
        return context
    
class SearchPostListView(ListView):
    model = Post
    template_name = "blog/post_list.html"
    context_object_name = "post"
    paginate_by = 5
    
    def get_queryset(self):
        self.query = self.request.GET.get('query') or ""
        
        queryset = super().get_queryset()
        if self.query:
            queryset = queryset.filter(Q(title__icontains=self.query) | Q(title__icontains=self.query))
        if not self.request.user.is_authenticated:
            queryset.filter(is_published=True)  
        self.post_count = len(queryset)
        
        
        return queryset 
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["query"] = self.query
        context["post_count"] = self.post_count
        return context
    
class CommentCreateView(CreateView):
    model = Comment
    form_class = CommentForm
    
    def form_valid(self, form): 
        comment = form.save(False)
        post_pk = self.kwargs['post_pk']
     
        post = get_object_or_404(Post, pk=post_pk) 
        comment.post = post
        comment.save()
        return redirect('post-Detail',pk=post_pk)
    def get_context_data(self, **kwargs) :
        context =super().get_context_data(**kwargs)
        post_pk = self.kwargs["post_pk"]
        context["post"] = get_object_or_404(Post,pk=post_pk)
        return context 
    
class ReplyCreateView(CreateView):
    model = Reply
    form_class = ReplyForm
    template_name = "blog/comment_form.html"
    
    def form_valid(self, form): 
        reply = form.save(False)
        comment_pk = self.kwargs['comment_pk']
        comment = get_object_or_404(Comment,pk=comment_pk)
        
        reply.comment = comment
        reply.save()
        return redirect('post-Detail',pk=comment.post.pk)
    def get_context_data(self, **kwargs) :
        context =super().get_context_data(**kwargs)
        comment_pk = self.kwargs["comment_pk"]
        context["comment"] = get_object_or_404(Comment,pk=comment_pk)
        return context 
    
class CommentDeleteView(LoginRequiredMixin,DeleteView):
    model = Comment
    template_name = "blog/comment_delete.html"
    
    def get_success_url(self) -> str:
        return reverse("post-Detail", kwargs={"pk":self.object.post.pk})
                                
    
class ReplyDeleteView(LoginRequiredMixin,DeleteView):
    model = Reply
    template_name = "blog/comment_delete.html"
    
    def get_success_url(self):
        return reverse("post-Detail", kwargs={"pk":self.object.comment.post.pk})
                                
    
    
    
    

blog/templates/blog/snippets/comments.html
{% if post.comment_set.all %}
<hr>
<h4 class="mb-4">コメント一覧</h4>
{% for comment in post.comment_set.all %}
<div class="comment mb-4">
    <b class="mb-2">{{ comment.name }} {{ comment.created_at }}</b>
    <a href="{% url 'reply' comment.pk %}"><i class="fa-solid fa-reply"></i></a>
 
    {% if user.is_authenticated %}
    <a href="{% url 'comment-delete' comment.pk %}"><i class="fa-solid fa-trash-can"></i></a>
    {% endif %}
    <p>{{ comment.text }}</p>
 
    {% for reply in comment.reply_set.all %}
    <div class="reply ms-4">
        <b>{{ reply.name }} {{ reply.created_at }}</b>
 
        {% if user.is_authenticated %}
        <a href="{% url 'reply-delete' reply.pk %}"><i class="fa-solid fa-trash-can"></i></a>
        {% endif %}
        <p>{{ reply.text }}</p>
    </div>
    {% endfor %}
</div>
{% endfor %}
{% endif %}

blog/templates/blog/snippets/footer.html
<footer class="mt-5" style="text-align: center;">
    <p><span lang="en">©</span> １班記録</p>
</footer>

blog/templates/blog/snippets/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-dark">
    <div class="container-fluid" >
      <a class="navbar-brand " href="{%url 'Post-List'%}" style="color: #bdc38f;">１班</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      
      <form class="d-flex" action="{% url 'search-Post-List' %}" method="GET">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="query">
        <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
    
    
    </div>
</nav>

blog/templates/blog/snippets/pagenation.html
{% load blog %}

{% if page_obj.has_previous %}
<!-- <a href="?page={{ page_obj.previous_page_number }}">前へ</a> -->
<a href="?{%  replace request 'page' page_obj.previous_page_number %}">前へ</a>
{% endif %}

{% for num in page_obj.paginator.page_range %}
{% if page_obj.number == num %}
<span>{{ num }}</span>
{% else %}
<!-- <a href="?page={{ num }}">{{ num }}</a> -->
<a href="?{%  replace request 'page' num %}">{{ num }}</a>
{% endif %}
{% endfor %}

{% if page_obj.has_next %}
<!-- <a href="?page={{ page_obj.next_page_number }}">次へ</a> -->
<a href="?{%  replace request 'page' page_obj.next_page_number %}">次へ</a>
{% endif %}

blog/templates/blog/snippets/sidebar.html
<div class = "p-1 ">
    <h4>カテゴリー</h4>
    <ul class="list-group list-group-flush">
        {% for category in categorys %}
        {% if category.count > 0 %}
            <li class="list-group-item">
                <a href="{%url 'category-Post-List' category.slug%}">
                    {{category.name}} ({{category.count}})
                    
                </a>    
            </li>
        {%endif%}
        {%endfor%}
       
    </ul>
</div>

<div class = "p-4">
    <h4>タグ</h4>
    {% for tag in tags %}
    
    <a href="{%url 'tag-Post-List' tag.slug%}" class="btn btn-dark">
        {{tag.name}}
    </a>   
   
    {%endfor%}
</div>
    